name: Build APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev python3-pip patch

      - name: Install Buildozer, Cython and Virtualenv
        run: |
          pip install --upgrade pip
          # Додаємо virtualenv, який критично необхідний для ізоляції збірок python-for-android
          pip install buildozer cython virtualenv

      - name: Auto-Accept Android SDK Licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          mkdir -p /home/runner/.buildozer/android/platform/android-sdk/licenses
          echo -e "\n893a416a975af43a3109d76e7c1269b0e56caa97\n24333f1a103b1de411902fd8574ec44744036102\n84831b9409646a918e30573bab4c9c91346d8abd" > /home/runner/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
          echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > /home/runner/.buildozer/android/platform/android-sdk/licenses/android-sdk-preview-license

      - name: Build Android APK
        run: |
          # Запускаємо пряму збірку без попереднього чищення неіснуючих папок
          buildozer -v android debug

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: YouTube-Downloader-APK
          path: bin/*.apk
